# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(262, 672)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(262, 594))
        MainWindow.setMaximumSize(QtCore.QSize(262, 794))
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(180, 620, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setAutoDefault(False)
        self.pushButton_1.setDefault(False)
        self.pushButton_1.setFlat(False)
        self.pushButton_1.setObjectName("pushButton_1")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_1.setGeometry(QtCore.QRect(10, 10, 241, 30))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        self.lineEdit_1.setFont(font)
        self.lineEdit_1.setInputMask("")
        self.lineEdit_1.setText("")
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(60, 595, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setObjectName("radioButton_3")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_4.setGeometry(QtCore.QRect(110, 595, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setChecked(False)
        self.radioButton_4.setObjectName("radioButton_4")
        self.buttonGroup_2.addButton(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_5.setGeometry(QtCore.QRect(160, 595, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        self.radioButton_5.setFont(font)
        self.radioButton_5.setChecked(False)
        self.radioButton_5.setObjectName("radioButton_5")
        self.buttonGroup_2.addButton(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_6.setGeometry(QtCore.QRect(30, 330, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        self.radioButton_6.setFont(font)
        self.radioButton_6.setChecked(True)
        self.radioButton_6.setObjectName("radioButton_6")
        self.buttonGroup_1 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_1.setObjectName("buttonGroup_1")
        self.buttonGroup_1.addButton(self.radioButton_6)
        self.radioButton_7 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_7.setGeometry(QtCore.QRect(80, 330, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        self.radioButton_7.setFont(font)
        self.radioButton_7.setObjectName("radioButton_7")
        self.buttonGroup_1.addButton(self.radioButton_7)
        self.radioButton_8 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_8.setGeometry(QtCore.QRect(130, 330, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        self.radioButton_8.setFont(font)
        self.radioButton_8.setObjectName("radioButton_8")
        self.buttonGroup_1.addButton(self.radioButton_8)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 250, 241, 30))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 360, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 390, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(170, 360, 20, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(170, 390, 20, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.groupBox_1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_1.setGeometry(QtCore.QRect(140, 470, 111, 121))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        self.groupBox_1.setFont(font)
        self.groupBox_1.setObjectName("groupBox_1")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.groupBox_1)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(10, 50, 91, 30))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_2.setFont(font)
        self.doubleSpinBox_2.setDecimals(1)
        self.doubleSpinBox_2.setMaximum(1.0)
        self.doubleSpinBox_2.setSingleStep(0.1)
        self.doubleSpinBox_2.setProperty("value", 1.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.doubleSpinBox_1 = QtWidgets.QDoubleSpinBox(self.groupBox_1)
        self.doubleSpinBox_1.setGeometry(QtCore.QRect(10, 20, 91, 30))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_1.setFont(font)
        self.doubleSpinBox_1.setWrapping(False)
        self.doubleSpinBox_1.setDecimals(1)
        self.doubleSpinBox_1.setMaximum(5.0)
        self.doubleSpinBox_1.setSingleStep(0.1)
        self.doubleSpinBox_1.setProperty("value", 0.3)
        self.doubleSpinBox_1.setObjectName("doubleSpinBox_1")
        self.spinBox_4 = QtWidgets.QSpinBox(self.groupBox_1)
        self.spinBox_4.setGeometry(QtCore.QRect(10, 80, 91, 30))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_4.setFont(font)
        self.spinBox_4.setSuffix("")
        self.spinBox_4.setMinimum(20000)
        self.spinBox_4.setMaximum(125000)
        self.spinBox_4.setSingleStep(5000)
        self.spinBox_4.setProperty("value", 20000)
        self.spinBox_4.setDisplayIntegerBase(10)
        self.spinBox_4.setObjectName("spinBox_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 470, 121, 121))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_2.setGeometry(QtCore.QRect(10, 50, 101, 30))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setMaximum(100)
        self.spinBox_2.setProperty("value", 6)
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_1 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_1.setGeometry(QtCore.QRect(10, 20, 101, 30))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_1.setFont(font)
        self.spinBox_1.setMinimum(1)
        self.spinBox_1.setMaximum(100)
        self.spinBox_1.setProperty("value", 10)
        self.spinBox_1.setDisplayIntegerBase(10)
        self.spinBox_1.setObjectName("spinBox_1")
        self.spinBox_3 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_3.setGeometry(QtCore.QRect(10, 80, 101, 30))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_3.setFont(font)
        self.spinBox_3.setSuffix("")
        self.spinBox_3.setMinimum(60)
        self.spinBox_3.setMaximum(3000)
        self.spinBox_3.setSingleStep(10)
        self.spinBox_3.setProperty("value", 600)
        self.spinBox_3.setObjectName("spinBox_3")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 650, 241, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_8.setFont(font)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setText("")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 620, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setDefault(False)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(130, 290, 121, 30))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setMaxLength(32764)
        self.lineEdit_9.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.radioButton_9 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_9.setGeometry(QtCore.QRect(180, 330, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        self.radioButton_9.setFont(font)
        self.radioButton_9.setObjectName("radioButton_9")
        self.buttonGroup_1.addButton(self.radioButton_9)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_3.setGeometry(QtCore.QRect(130, 210, 121, 32))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_3.setFont(font)
        self.doubleSpinBox_3.setMaximum(1000.0)
        self.doubleSpinBox_3.setSingleStep(0.05)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 210, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.lineEdit_5 = QtWidgets.QSpinBox(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(100, 360, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setMinimum(-1000000)
        self.lineEdit_5.setMaximum(1000000)
        self.lineEdit_5.setSingleStep(25)
        self.lineEdit_5.setProperty("value", 300)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QSpinBox(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(180, 360, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setMinimum(-1000000)
        self.lineEdit_6.setMaximum(1000000)
        self.lineEdit_6.setSingleStep(25)
        self.lineEdit_6.setProperty("value", 400)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(130, 90, 121, 32))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(10, 50, 241, 30))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setText("")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.checkBox_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_1.setGeometry(QtCore.QRect(10, 170, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        self.checkBox_1.setFont(font)
        self.checkBox_1.setObjectName("checkBox_1")
        self.comboBox_1 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_1.setGeometry(QtCore.QRect(130, 170, 121, 32))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        self.comboBox_1.setFont(font)
        self.comboBox_1.setEditable(False)
        self.comboBox_1.setObjectName("comboBox_1")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.lineEdit_4 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(130, 130, 121, 32))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setDecimals(3)
        self.lineEdit_4.setMinimum(-1000.0)
        self.lineEdit_4.setMaximum(1000.0)
        self.lineEdit_4.setSingleStep(10.0)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_7 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(100, 390, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setDecimals(1)
        self.lineEdit_7.setMinimum(-100000.0)
        self.lineEdit_7.setMaximum(100000.0)
        self.lineEdit_7.setSingleStep(25.0)
        self.lineEdit_7.setProperty("value", -400.0)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(180, 390, 71, 32))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setDecimals(1)
        self.lineEdit_8.setMinimum(-100000.0)
        self.lineEdit_8.setMaximum(100000.0)
        self.lineEdit_8.setSingleStep(25.0)
        self.lineEdit_8.setProperty("value", 100.0)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 620, 91, 30))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_4.setGeometry(QtCore.QRect(100, 430, 71, 32))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_4.setFont(font)
        self.doubleSpinBox_4.setDecimals(3)
        self.doubleSpinBox_4.setMaximum(1000.0)
        self.doubleSpinBox_4.setSingleStep(0.05)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_5.setGeometry(QtCore.QRect(180, 430, 71, 32))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_5.setFont(font)
        self.doubleSpinBox_5.setDecimals(3)
        self.doubleSpinBox_5.setMinimum(0.0)
        self.doubleSpinBox_5.setMaximum(1000.0)
        self.doubleSpinBox_5.setSingleStep(0.05)
        self.doubleSpinBox_5.setProperty("value", 0.15)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 430, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 290, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono")
        font.setPointSize(7)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.comboBox_1.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.radioButton_4, self.radioButton_5)
        MainWindow.setTabOrder(self.radioButton_5, self.pushButton_1)
        MainWindow.setTabOrder(self.pushButton_1, self.radioButton_3)
        MainWindow.setTabOrder(self.radioButton_3, self.radioButton_6)
        MainWindow.setTabOrder(self.radioButton_6, self.lineEdit_1)
        MainWindow.setTabOrder(self.lineEdit_1, self.radioButton_7)
        MainWindow.setTabOrder(self.radioButton_7, self.radioButton_8)
        MainWindow.setTabOrder(self.radioButton_8, self.lineEdit_3)
        MainWindow.setTabOrder(self.lineEdit_3, self.doubleSpinBox_2)
        MainWindow.setTabOrder(self.doubleSpinBox_2, self.doubleSpinBox_1)
        MainWindow.setTabOrder(self.doubleSpinBox_1, self.spinBox_2)
        MainWindow.setTabOrder(self.spinBox_2, self.spinBox_1)
        MainWindow.setTabOrder(self.spinBox_1, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.spinBox_3)
        MainWindow.setTabOrder(self.spinBox_3, self.spinBox_4)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ABF Plot"))
        self.pushButton_1.setText(_translate("MainWindow", "Save"))
        self.lineEdit_1.setPlaceholderText(_translate("MainWindow", "ABF file names separated by spaces"))
        self.label_2.setText(_translate("MainWindow", "Impact chenged at:\n"
"(separated by spaces)"))
        self.radioButton_3.setText(_translate("MainWindow", "PNG"))
        self.radioButton_4.setText(_translate("MainWindow", "SVG"))
        self.radioButton_5.setText(_translate("MainWindow", "EPS"))
        self.radioButton_6.setText(_translate("MainWindow", "VC"))
        self.radioButton_7.setText(_translate("MainWindow", "IC"))
        self.radioButton_8.setText(_translate("MainWindow", "CA"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Description"))
        self.label_4.setText(_translate("MainWindow", "Vertical offset:"))
        self.label_3.setText(_translate("MainWindow", "X, (min:max):"))
        self.label_5.setText(_translate("MainWindow", "Y, (min:max):"))
        self.label_6.setText(_translate("MainWindow", " :"))
        self.label_7.setText(_translate("MainWindow", " :"))
        self.groupBox_1.setTitle(_translate("MainWindow", "Line:"))
        self.doubleSpinBox_2.setPrefix(_translate("MainWindow", "alpha: "))
        self.doubleSpinBox_1.setPrefix(_translate("MainWindow", "width: "))
        self.spinBox_4.setPrefix(_translate("MainWindow", "freq:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Figure:"))
        self.spinBox_2.setSuffix(_translate("MainWindow", " in"))
        self.spinBox_2.setPrefix(_translate("MainWindow", "height: "))
        self.spinBox_1.setSuffix(_translate("MainWindow", " in"))
        self.spinBox_1.setPrefix(_translate("MainWindow", "width:  "))
        self.spinBox_3.setPrefix(_translate("MainWindow", "dpi:    "))
        self.pushButton_2.setText(_translate("MainWindow", "Preview"))
        self.lineEdit_9.setText(_translate("MainWindow", "0"))
        self.lineEdit_9.setPlaceholderText(_translate("MainWindow", "Exclude sweeps (comma separated)"))
        self.radioButton_9.setText(_translate("MainWindow", "CAP"))
        self.label_9.setText(_translate("MainWindow", "Gaussian Filter \n"
"(sigma):"))
        self.lineEdit_2.setText(_translate("MainWindow", "0"))
        self.lineEdit_10.setPlaceholderText(_translate("MainWindow", "Impacts ( + or - ) separated by spaces"))
        self.checkBox_1.setText(_translate("MainWindow", "2 window mode"))
        self.comboBox_1.setCurrentText(_translate("MainWindow", "Channel 0"))
        self.comboBox_1.setItemText(0, _translate("MainWindow", "Channel 0"))
        self.comboBox_1.setItemText(1, _translate("MainWindow", "Channel 1"))
        self.comboBox_1.setItemText(2, _translate("MainWindow", "Both (2 windows)"))
        self.pushButton_3.setText(_translate("MainWindow", "Memb. Test"))
        self.checkBox_2.setText(_translate("MainWindow", "Baseline (s):"))
        self.label.setText(_translate("MainWindow", "Traces to exclude:\n"
"(separated by comma)"))
